### ISSUE TITLE
ImportError: cannot import name 'InferenNet_fastRes50'

### ISSUE THREAD

**Issue by CherrySXY** [GajuuzZ/Human-Falling-Detect-Tracks#31]
Traceback (most recent call last):
  File "D:/installedProjects/PyCharm_Projects/Human-Falling-Detect-Tracks/main.py", line 12, in <module>
    from PoseEstimateLoader import SPPE_FastPose
  File "D:\installedProjects\PyCharm_Projects\Human-Falling-Detect-Tracks\PoseEstimateLoader.py", line 5, in <module>
    from SPPE.src.main_fast_inference import InferenNet_fast, InferenNet_fastRes50
ImportError: cannot import name 'InferenNet_fastRes50'

**Comment by GajuuzZ** [comment]
I didn't write the code to handle import path correctly (like adding __init__.py to all module folder). So try to import other way.
