### ISSUE TITLE
A Problem in the create_dataset_2.py

### ISSUE THREAD

**Issue by YeungChiu** [GajuuzZ/Human-Falling-Detect-Tracks#43]
Hi , I have a problem confused me.
’‘’
Loading pose model from ./Models/sppe/fast_res50_256x192.pth
Process on: video (1).avi
Process on: video (10).avi
Traceback (most recent call last):
  File "/home/wangliu/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'video'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create_dataset_2.py", line 142, in <module>
    frames_label = annot[annot['video'] == vid].reset_index(drop=True)
  File "/home/wangliu/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/wangliu/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'video'
‘’‘
When I run the Python file,  it occured some times that in the program, then I debug it. Then I found  that the first video is normal, the second video do not work.
I'd appreciate any information someone could give me.

**Comment by YeungChiu** [comment]
It is solved.

**Comment by Tyh19971201** [comment]
> It is solved.
Process on: 1.mp4
Traceback (most recent call last):
  File "/home/tyh/Human-Falling-Detect-Tracks/Data/create_dataset_2.py", line 62, in <module>
    frames_label = annot[annot['video'] == vid].reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
你好，请问你这个问题是怎么解决的呀，我也有这个问题，特别希望能解答一下，非常感谢哈。

**Comment by cyoungx** [comment]
您好，首先很抱歉现在才看到。
这个问题我也遇到过。
可能有两个原因。
（1）一个是索引问题
也就是视频第几个帧数和计算机运行的第几个帧数不一致。最常见的就是第一帧和最后一帧。
（2）图片真的就没输进去
以上都是我碰到过的问题。我是在问题前一步一步调试分析输出内容发现的。、
祝您顺利。



在 2021-11-09 15:03:19，"Tyh19971201" ***@***.***> 写道：

It is solved.
Process on: 1.mp4
Traceback (most recent call last):
File "/home/tyh/Human-Falling-Detect-Tracks/Data/create_dataset_2.py", line 62, in
frames_label = annot[annot['video'] == vid].reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
你好，请问你这个问题是怎么解决的呀，我也有这个问题，特别希望能解答一下，非常感谢哈。

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heavenluv** [comment]
请问到最后是通过修改什么成功运行啊？

**Comment by LJS999-Liu** [comment]
> It is solved.

你好，请问你是怎么解决这个问题的

**Comment by cosao** [comment]
> 您好，首先很抱歉现在才看到。 这个问题我也遇到过。 可能有两个原因。 （1）一个是索引问题 也就是视频第几个帧数和计算机运行的第几个帧数不一致。最常见的就是第一帧和最后一帧。 （2）图片真的就没输进去 以上都是我碰到过的问题。我是在问题前一步一步调试分析输出内容发现的。、 祝您顺利。 在 2021-11-09 15:03:19，"Tyh19971201" ***@***.***> 写道： It is solved. Process on: 1.mp4 Traceback (most recent call last): File "/home/tyh/Human-Falling-Detect-Tracks/Data/create_dataset_2.py", line 62, in frames_label = annot[annot['video'] == vid].reset_index(drop=True) TypeError: 'NoneType' object is not subscriptable 你好，请问你这个问题是怎么解决的呀，我也有这个问题，特别希望能解答一下，非常感谢哈。 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

-----------------------------------------------------------------------------------------------

Can you explain solution for me?
