### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by mzc688** [GajuuzZ/Human-Falling-Detect-Tracks#51]
The full error is :
Traceback (most recent call last):
  File "E:/Human-Falling-Detect-Tracks-master/main.py", line 106, in <module>
    frame = cam.getitem()
  File "E:\Human-Falling-Detect-Tracks-master\CameraLoader.py", line 58, in getitem
    frame = self.frame.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
How do I fix this error? Any help would be gladly appreciated.

**Comment by MaarufB** [comment]
I am encountering that same issue using webcam. I just have to close the terminal then open it again and run the main.py again

**Comment by GajuuzZ** [comment]
I have fixed that in the CameraLoader. It was because I let the program get a frame too fast before the camera thread actually run.
