### ISSUE TITLE
I Have Question create_dataset_2.py !

### ISSUE THREAD

**Issue by moonnyeon** [GajuuzZ/Human-Falling-Detect-Tracks#69]
In (create_dataset_2.py)

The used code is 
******************************************************************************
(#create_dataset_2.py)

inp_h = 320
inp_w = 256
pose_estimator = SPPE_FastPose(inp_h, inp_w)
******************************************************************************

but If you go to the actual SPPE_FastPose class
(#PoseEstimateLoader.py)
**************************************************
class SPPE_FastPose(object):
    def __init__(self,
                 backbone,
                 input_height=320,
                 input_width=256,
                 device='cuda'):
        assert backbone in ['resnet50', 'resnet101'], '{} backbone is not support yet!'.format(backbone)
******************************************************************************

implemented like this

But nobody asked about this in create_dataset_2, so I leave it 

this is my error

/workspace/falldown/Human-Falling-Detect-Tracks-master$ python3 create_dataset_2.py 
Traceback (most recent call last):
  File "create_dataset_2.py", line 30, in <module>
    pose_estimator = SPPE_FastPose(inp_h, inp_w)
  File "/home/dskim/workspace/falldown/Human-Falling-Detect-Tracks-master/PoseEstimateLoader.py", line 17, in __init__
    assert backbone in ['resnet50', 'resnet101'], '{} backbone is not support yet!'.format(backbone)
AssertionError: 320 backbone is not support yet!

**Comment by GajuuzZ** [comment]
Yes, I edit my module and forget to edit in the old code, So sometimes you should your intuition to fix it. And I don't recommend using these create_dataset scripts without understanding what each line does. Because I provided it as an example of how to pre-process on my dataset, it may not work on your data if the format is not the same.

**Comment by moonnyeon** [comment]
> Yes, I edit my module and forget to edit in the old code, So sometimes you should your intuition to fix it. And I don't recommend using these create_dataset scripts without understanding what each line does. Because I provided it as an example of how to pre-process on my dataset, it may not work on your data if the format is not the same.

thank you very much for your answer ! 
have a good day!

**Comment by 15551218648** [comment]
> > Yes, I edit my module and forget to edit in the old code, So sometimes you should your intuition to fix it. And I don't recommend using these create_dataset scripts without understanding what each line does. Because I provided it as an example of how to pre-process on my dataset, it may not work on your data if the format is not the same.
> 
> thank you very much for your answer ! have a good day!

Hi, have you solved this problem? Could you teach me how to modify the create_dataset_2.py.
 And another question :I can't find the file : '/Data/falldata/Home/Annotation_files'  # bounding box annotation for each frame. Where is this file and what is it?
Looking forward to your recovery，thanks very much.

**Comment by liumingzhu6060** [comment]
hello, have you got the dataset, Could you send me a copy，thank you, my email is liumingzhu6060@163.com

**Comment by wangfeifeifeifei** [comment]
Hi, have you solved this problem?
